
services:
    
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: service-booking-system-backend
    ports:
      - "${DOCKER_SPRING_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:${DB_PORT}/${DOCKER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DOCKER_DB_HOST}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env 

networks:
  app_network:
    driver: bridge
